openapi: 3.0.3
info:
  title: LeaseRate service
  description: REST Composite service about leaseRate details
  version: 0.1.0
paths:
  '/cars/{id}/leaserate':
    get:
      tags:
        - leaseRate
      summary: Retrieve lease rate details
      operationId: get
      parameters:
        - name: id
          in: path
          description: id of car
          required: true
          schema:
            type: integer
        - name: mileage
          in: query
          description: the amount of kilometers on annual base
          required: true
          schema:
            type: integer
        - name: duration
          in: query
          description: the number of months in the contract
          required: true
          schema:
            type: integer
        - name: interestrate
          in: query
          description: Interest rate with startdate
          required: true
          schema:
            type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LeaseRateDetails'
        "404":
          description: Car not found
        "400":
          description: Bad request
        "500":
          description: Internal server error

components:
  schemas:
    LeaseRateDetails:
      type: object
      properties:
        leaseRate:
          type: number