version: "3.8"
services:
  carDB:
    image: mysql:8.0
    ports:
      - 3307:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=carDB
  customerDB:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=customerDB
  carservice:
    image: quarkus/carservice-jvm:latest
    ports:
      - 8001:8001
  customerservice:
    image: quarkus/customerservice-jvm:latest
    ports:
      - 8000:8000
  gatewayapi:
    image: quarkus/gatewayapi-jvm:latest
    ports:
      - 8003:8003
  leaserateservice:
    image: quarkus/leaserateservice-jvm:latest
    ports:
      - 8002:8002